version: '3.8'

services:
  backend:
    build: ./app
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://cartman:Tutorat@cluster0.kagzlna.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - MONGO_DB_NAME=Medlink
    command: uvicorn main:app --host 0.0.0.0 --port 8000
